package es.jaga.fastfoodcompany.vista;

import es.jaga.fastfoodcompany.controlador.AccionDetalleVenta;
import es.jaga.fastfoodcompany.controlador.AccionVentas;
import es.jaga.fastfoodcompany.modelo.entidades.DetalleVenta;
import es.jaga.fastfoodcompany.modelo.entidades.Venta;
import es.jaga.fastfoodcompany.principal.FFCJFrame;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Classe del panel de pedidos por id cleinte.
 * @author Jose Antonio González Alcántara
 */
public class PanelVentasProductosCliente extends javax.swing.JPanel {

    private final FFCJFrame frame;
    private static final String[] NOMBRE_COLUMNAS_TABLA_VENTAS = {"Id del cliente", "Numero de venta","Total venta","Fecha de la venta"};
    private static final String[] NOMBRE_COLUMNAS_TABLA_DETALLES = {"Id Producto", "Numero de venta","Cantidad","Precio venta"};
    private DefaultTableModel tablaVentas;
    private DefaultTableModel tablaDetalleVentas;
    private Venta venta;
    private DetalleVenta detalleVenta;
    private List listaVentas;
    private AccionVentas acciones;
    private AccionDetalleVenta accionesDetalle;
    private final DateFormat formatoFecha =  new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form PanelVentasProductosCliente
     * @param frame
     */
    public PanelVentasProductosCliente(FFCJFrame frame) {
        initComponents();
        this.frame = frame;
        this.tablaVentas = new DefaultTableModel(NOMBRE_COLUMNAS_TABLA_VENTAS,0);
        this.tablaDetalleVentas = new DefaultTableModel(NOMBRE_COLUMNAS_TABLA_DETALLES,0);
        this.listaVentas = new ArrayList();
        this.acciones = new AccionVentas();
        this.accionesDetalle = new AccionDetalleVenta();
        this.actualizarTablaVentas(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSuperior = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        pnlInferior = new javax.swing.JPanel();
        scrTicket = new javax.swing.JScrollPane();
        tblTickets = new javax.swing.JTable();
        scrVentas = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Pedidos por cliente"));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout(5, 5));

        pnlSuperior.setPreferredSize(new java.awt.Dimension(800, 40));

        lblCliente.setText("Introduce la id del cliente:");

        btnBuscar.setText("Buscar ventas ");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSuperiorLayout = new javax.swing.GroupLayout(pnlSuperior);
        pnlSuperior.setLayout(pnlSuperiorLayout);
        pnlSuperiorLayout.setHorizontalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblCliente)
                .addGap(5, 5, 5)
                .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar))
        );
        pnlSuperiorLayout.setVerticalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblCliente))
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(btnBuscar))
        );

        add(pnlSuperior, java.awt.BorderLayout.NORTH);

        pnlInferior.setPreferredSize(new java.awt.Dimension(795, 500));

        tblTickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTickets.setPreferredSize(new java.awt.Dimension(390, 590));
        scrTicket.setViewportView(tblTickets);

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVentasMouseClicked(evt);
            }
        });
        scrVentas.setViewportView(tblVentas);

        javax.swing.GroupLayout pnlInferiorLayout = new javax.swing.GroupLayout(pnlInferior);
        pnlInferior.setLayout(pnlInferiorLayout);
        pnlInferiorLayout.setHorizontalGroup(
            pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInferiorLayout.createSequentialGroup()
                .addComponent(scrVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrTicket, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE))
        );
        pnlInferiorLayout.setVerticalGroup(
            pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInferiorLayout.createSequentialGroup()
                .addGroup(pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addComponent(scrTicket))
                .addGap(385, 385, 385))
        );

        add(pnlInferior, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String idCliente = this.txtIdCliente.getText();
        if (esNumero(idCliente) && !idCliente.isEmpty()) {
            actualizarTablaVentas(Integer.parseInt(idCliente));
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVentasMouseClicked
        int fila = this.tblVentas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila.");
        } else {
            int numeroDeVenta = (int) tblVentas.getValueAt(fila, 1);
            actualizarTablaTicket(numeroDeVenta);
        }
    }//GEN-LAST:event_tblVentasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JPanel pnlInferior;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JScrollPane scrTicket;
    private javax.swing.JScrollPane scrVentas;
    private javax.swing.JTable tblTickets;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtIdCliente;
    // End of variables declaration//GEN-END:variables

    private void actualizarTablaVentas(int idCliente){
        int i = this.tablaVentas.getRowCount();
        while (i >= 1) {
            i--;
            this.tablaVentas.removeRow(i);
        }
        this.listaVentas = this.acciones.obtenerVentasIdCliente(idCliente);
        if (this.listaVentas == null) {
            this.listaVentas = new ArrayList();
        }
        Iterator<Venta> iteratorClientes = this.listaVentas.iterator();
        while (iteratorClientes.hasNext()) {
            this.venta =  iteratorClientes.next();
            Vector filaTabla = new Vector(NOMBRE_COLUMNAS_TABLA_VENTAS.length);
            filaTabla.add(this.venta.getCliente());
            filaTabla.add(this.venta.getNumeroDeVenta());
            filaTabla.add(this.venta.getTotal());
            filaTabla.add(this.venta.getFecha());
            this.tablaVentas.addRow(filaTabla);
            this.tblVentas.setModel(this.tablaVentas);
            this.scrVentas.setViewportView(this.tblVentas);
        }   
    }
    
private void actualizarTablaTicket(int numeroDeVenta){
        int i = this.tablaDetalleVentas.getRowCount();
        while (i >= 1) {
            i--;
            this.tablaDetalleVentas.removeRow(i);
        }
        this.listaVentas = this.accionesDetalle.obtenerDetallesVenta(numeroDeVenta);
        if (this.listaVentas == null) {
            this.listaVentas = new ArrayList();
        }
        Iterator<DetalleVenta> iteratorClientes = this.listaVentas.iterator();
        while (iteratorClientes.hasNext()) {
            this.detalleVenta =  iteratorClientes.next();
            Vector filaTabla = new Vector(NOMBRE_COLUMNAS_TABLA_DETALLES.length);
            filaTabla.add(this.detalleVenta.getIdProducto());
            filaTabla.add(this.detalleVenta.getNumeroDeVenta());
            filaTabla.add(this.detalleVenta.getCantidad());
            filaTabla.add(this.detalleVenta.getPrecioVenta());
            this.tablaDetalleVentas.addRow(filaTabla);
            this.tblTickets.setModel(this.tablaDetalleVentas);
            this.scrTicket.setViewportView(this.tblTickets);
        }   
    }
    
    private boolean esNumero(String texto){
        try {
            Integer.parseInt(texto);
            return true;
        } catch (Exception ex) {
            return false;
        }
    }
}
