package es.jaga.fastfoodcompany.vista;

/**
 * Classe del selector de Archivos.
 * 
 * @author Jose Antonio González Alcántara
 */
public class SelectorDeArchivos extends javax.swing.JPanel {

    /**
     * Creates new form SelectorDeArchivos
     */
    public SelectorDeArchivos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgSelectorArchivos = new javax.swing.JDialog();
        flcSelectorDeArchivos = new javax.swing.JFileChooser();

        javax.swing.GroupLayout dlgSelectorArchivosLayout = new javax.swing.GroupLayout(dlgSelectorArchivos.getContentPane());
        dlgSelectorArchivos.getContentPane().setLayout(dlgSelectorArchivosLayout);
        dlgSelectorArchivosLayout.setHorizontalGroup(
            dlgSelectorArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dlgSelectorArchivosLayout.setVerticalGroup(
            dlgSelectorArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flcSelectorDeArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flcSelectorDeArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dlgSelectorArchivos;
    private javax.swing.JFileChooser flcSelectorDeArchivos;
    // End of variables declaration//GEN-END:variables
}
