version: "3.9"
services:
  web:
    build: .
    image: jagascripts/landing:dev
    command: gunicorn run:app -b 0.0.0.0:8000 -w 2
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

